### PR TITLE
Add AUR package link

### PR DESCRIPTION
**Pull request by Siphonay**
As requested on Reddit!

### CODE REVIEW

**Comment by sdushantha** [comment]
@Siphonay In the package, you use another `colorpicker`.
The one this project uses is this one: https://github.com/ym1234/colorpicker

**Comment by Siphonay** [comment]
Yes, I am looking into taking ownership of the colorpicker package or the AUR, or find another solution if that doesn't happen. I'll get back to you when that happens so you can merge

**Comment by ghost** [comment]
@Siphonay  I have added Wayland dependencies too In README.md in my pull request.If mine gets merged,it's gonna conflict. Please correct your README.md(Modify after my PR gets merged) .

**Comment by Siphonay** [comment]
@varshitgithub will do!

**Comment by sdushantha** [comment]
@Siphonay I have merged Wayland PR

**Comment by sdushantha** [comment]
@Siphonay Just thought of pinging you and letting you know that you can now upload `farge` to the AUR when you have time :)

**Comment by Barbaross93** [comment]
I have now taken ownership of the [AUR](https://aur.archlinux.org/packages/farge-git/) package. It now points to the correct colorpicker dependency. Feel free to merge this/ add a link/instructions for the AUR package

**Comment by sdushantha** [comment]
@Barbarossa93 Thank you for letting me know! I'll merge this PR right away!

**Pull request merged**
