### PR TITLE
Add gpick as a alternative colorpicker

### PR DESCRIPTION
**Pull request by Barbaross93**
Hey @sdushantha 

Turns out this was a simple addition, so I went ahead and implemented it myself. Let me know if I should change anything; the only thing I'm unsure of in terms of implementation is the dependency check. It works, but I'm not sure if you have a better idea in mind.

### CODE REVIEW

**Comment by Barbaross93** [comment]
Shoot, I can make changes to the README if you like as well! Forgot to do that here

**Comment by sdushantha** [comment]
Hey @Barbarossa93,

I took a look at `gpick` and I dont think it something I want to add to `farge`. This is because `gpick`uses a GTK GUI and there is no way to hide/disable it. I personally think that if you want to use `gpick` then it would be best to stick with it instead of using `farge`  with `gpick`as a backend because it more features.

**Comment by Barbaross93** [comment]
No worries, totally understandable. The gui is hideable, but gpick is probably overkill for this project as a dependency anyway. How would you feel about [xcolor](https://github.com/Soft/xcolor) instead?

**Comment by sdushantha** [comment]
> How would you feel about xcolor instead?

Haha thats what I'm currently working on! 

I've been using `xcolor` by itself for a while now and I thought it would be neat to integrate it with `farge`. The only flaw with `xcolor` is that there is no way of cancelling or quitting it. So the user must click somewhere and select a color. This can be annoying as the color code will get put into the clipboard which may cause the loss of important text that was copied earlier.

**Pull request closed without merging**
